In [1]:
import pandas as pd

## Summary Stats

In [3]:
df = pd.read_csv('../data/vgchartz-2024.csv')

In [4]:
df.head()

,img,title,console,genre,publisher,developer,critic_score,total_sales,na_sales,jp_sales,pal_sales,other_sales,release_date,last_update
0,/games/boxart/full_6510540AmericaFrontccc.jpg,Grand Theft Auto V,PS3,Action,Rockstar Games,Rockstar North,9.4,20.32,6.37,0.99,9.85,3.12,2013-09-17,NaN
1,/games/boxart/full_5563178AmericaFrontccc.jpg,Grand Theft Auto V,PS4,Action,Rockstar Games,Rockstar North,9.7,19.39,6.06,0.60,9.71,3.02,2014-11-18,2018-01-03
2,/games/boxart/827563ccc.jpg,Grand Theft Auto: Vice City,PS2,Action,Rockstar Games,Rockstar North,9.6,16.15,8.41,0.47,5.49,1.78,2002-10-28,NaN
3,/games/boxart/full_9218923AmericaFrontccc.jpg,Grand Theft Auto V,X360,Action,Rockstar Games,Rockstar North,NaN,15.86,9.06,0.06,5.33,1.42,2013-09-17,NaN
4,/games/boxart/full_4990510AmericaFrontccc.jpg,Call of Duty: Black Ops 3,PS4,Shooter,Activision,Treyarch,8.1,15.09,6.18,0.41,6.05,2.44,2015-11-06,2018-01-14

In [5]:
df.describe()

,critic_score,total_sales,na_sales,jp_sales,pal_sales,other_sales
count,6678.000000,18922.000000,12637.000000,6726.000000,12824.000000,15128.000000
mean,7.220440,0.349113,0.264740,0.102281,0.149472,0.043041
std,1.457066,0.807462,0.494787,0.168811,0.392653,0.126643
min,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,6.400000,0.030000,0.050000,0.020000,0.010000,0.000000
50%,7.500000,0.120000,0.120000,0.040000,0.040000,0.010000
75%,8.300000,0.340000,0.280000,0.120000,0.140000,0.030000
max,10.000000,20.320000,9.760000,2.130000,9.850000,3.120000

In [7]:
df.columns

Index(['img', 'title', 'console', 'genre', 'publisher', 'developer',
       'critic_score', 'total_sales', 'na_sales', 'jp_sales', 'pal_sales',
       'other_sales', 'release_date', 'last_update'],
      dtype='object')

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 64016 entries, 0 to 64015
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   img           64016 non-null  object
 1   title         64016 non-null  object
 2   console       64016 non-null  object
 3   genre         64016 non-null  object
 4   publisher     64016 non-null  object
 5   developer     63999 non-null  object
 6   critic_score  6678 non-null   float64
 7   total_sales   18922 non-null  float64
 8   na_sales      12637 non-null  float64
 9   jp_sales      6726 non-null   float64
 10  pal_sales     12824 non-null  float64
 11  other_sales   15128 non-null  float64
 12  release_date  56965 non-null  object
 13  last_update   17879 non-null  object
dtypes: float64(6), object(8)
memory usage: 6.8+ MB

In [9]:
print("Shape:", df.shape)
print("\nData Types:\n", df.dtypes)
print("\nMissing Values:\n", df.isna().sum())
print("\nSummary Stats:\n", df.describe(include='all'))

Shape: (64016, 14)

Data Types:
 img              object
title            object
console          object
genre            object
publisher        object
developer        object
critic_score    float64
total_sales     float64
na_sales        float64
jp_sales        float64
pal_sales       float64
other_sales     float64
release_date     object
last_update      object
dtype: object

Missing Values:
 img                 0
title               0
console             0
genre               0
publisher           0
developer          17
critic_score    57338
total_sales     45094
na_sales        51379
jp_sales        57290
pal_sales       51192
other_sales     48888
release_date     7051
last_update     46137
dtype: int64

Summary Stats:
                               img               title console  genre  \
count                       64016               64016   64016  64016
unique                      56177               39798      81     20
top     /games/boxart/default.jpg  Plants vs. Zombies      PC   Misc
freq                         7810                  17   12617   9304
mean                          NaN                 NaN     NaN    NaN
std                           NaN                 NaN     NaN    NaN
min                           NaN                 NaN     NaN    NaN
25%                           NaN                 NaN     NaN    NaN
50%                           NaN                 NaN     NaN    NaN
75%                           NaN                 NaN     NaN    NaN
max                           NaN                 NaN     NaN    NaN

       publisher developer  critic_score   total_sales      na_sales  \
count      64016     63999   6678.000000  18922.000000  12637.000000
unique      3383      8862           NaN           NaN           NaN
top      Unknown   Unknown           NaN           NaN           NaN
freq        8842      4435           NaN           NaN           NaN
mean         NaN       NaN      7.220440      0.349113      0.264740
std          NaN       NaN      1.457066      0.807462      0.494787
min          NaN       NaN      1.000000      0.000000      0.000000
25%          NaN       NaN      6.400000      0.030000      0.050000
50%          NaN       NaN      7.500000      0.120000      0.120000
75%          NaN       NaN      8.300000      0.340000      0.280000
max          NaN       NaN     10.000000     20.320000      9.760000

           jp_sales     pal_sales   other_sales release_date last_update
count   6726.000000  12824.000000  15128.000000        56965       17879
unique          NaN           NaN           NaN         7922        1545
top             NaN           NaN           NaN   1994-01-01  2018-01-06
freq            NaN           NaN           NaN          515         165
mean       0.102281      0.149472      0.043041          NaN         NaN
std        0.168811      0.392653      0.126643          NaN         NaN
min        0.000000      0.000000      0.000000          NaN         NaN
25%        0.020000      0.010000      0.000000          NaN         NaN
50%        0.040000      0.040000      0.010000          NaN         NaN
75%        0.120000      0.140000      0.030000          NaN         NaN
max        2.130000      9.850000      3.120000          NaN         NaN